default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: url_dev
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: url_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: url_prod
  username: hey-url
  password: <%= ENV['HEY-URL_DATABASE_PASSWORD'] %>
